services:
  nginx:
    container_name: yii_nginx
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    networks:
      - yii
    depends_on:
      - php
  php:
    container_name: yii_php
    build: ./docker/php
    volumes:
      - ./backend:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - yii
    depends_on:
      - mysql
  mysql:
    container_name: yii_mysql
    image: mysql:8.0
    volumes:
      # - ./www:/var/www
      # - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_USER=yii
      - MYSQL_PASSWORD=yii
      - MYSQL_ROOT_PASSWORD=yii
      - MYSQL_DATABASE=yii
    command: ["--default-authentication-plugin=mysql_native_password"]
    networks:
      - yii

networks:
  yii:

volumes:
  db:
